/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPredictionsRouteImport } from './routes/api/predictions'
import { Route as ApiPlayersRouteImport } from './routes/api/players'
import { Route as ApiInitRouteImport } from './routes/api/init'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiMatchesResultRouteImport } from './routes/api/matches/result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPredictionsRoute = ApiPredictionsRouteImport.update({
  id: '/api/predictions',
  path: '/api/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayersRoute = ApiPlayersRouteImport.update({
  id: '/api/players',
  path: '/api/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInitRoute = ApiInitRouteImport.update({
  id: '/api/init',
  path: '/api/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesResultRoute = ApiMatchesResultRouteImport.update({
  id: '/api/matches/result',
  path: '/api/matches/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/data': typeof ApiDataRoute
  '/api/init': typeof ApiInitRoute
  '/api/players': typeof ApiPlayersRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/matches/result': typeof ApiMatchesResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/data': typeof ApiDataRoute
  '/api/init': typeof ApiInitRoute
  '/api/players': typeof ApiPlayersRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/matches/result': typeof ApiMatchesResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/data': typeof ApiDataRoute
  '/api/init': typeof ApiInitRoute
  '/api/players': typeof ApiPlayersRoute
  '/api/predictions': typeof ApiPredictionsRoute
  '/api/matches/result': typeof ApiMatchesResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/data'
    | '/api/init'
    | '/api/players'
    | '/api/predictions'
    | '/api/matches/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/data'
    | '/api/init'
    | '/api/players'
    | '/api/predictions'
    | '/api/matches/result'
  id:
    | '__root__'
    | '/'
    | '/api/data'
    | '/api/init'
    | '/api/players'
    | '/api/predictions'
    | '/api/matches/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiInitRoute: typeof ApiInitRoute
  ApiPlayersRoute: typeof ApiPlayersRoute
  ApiPredictionsRoute: typeof ApiPredictionsRoute
  ApiMatchesResultRoute: typeof ApiMatchesResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/predictions': {
      id: '/api/predictions'
      path: '/api/predictions'
      fullPath: '/api/predictions'
      preLoaderRoute: typeof ApiPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/players': {
      id: '/api/players'
      path: '/api/players'
      fullPath: '/api/players'
      preLoaderRoute: typeof ApiPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/init': {
      id: '/api/init'
      path: '/api/init'
      fullPath: '/api/init'
      preLoaderRoute: typeof ApiInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/result': {
      id: '/api/matches/result'
      path: '/api/matches/result'
      fullPath: '/api/matches/result'
      preLoaderRoute: typeof ApiMatchesResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDataRoute: ApiDataRoute,
  ApiInitRoute: ApiInitRoute,
  ApiPlayersRoute: ApiPlayersRoute,
  ApiPredictionsRoute: ApiPredictionsRoute,
  ApiMatchesResultRoute: ApiMatchesResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
